#!/bin/bash

#Author : NBS
#Description : To get the list of collborators/users having access to a repository.
#Date : 14th December,2025 

# Pre-requisites : 
# 1) Run export username="USERNAME"
# 2) Create a Personal Access Token(Classic) by going to the Developer Settings in the Profile.
# 3) Run export token="TOKEN" , in the terminal to store the creds locally.(Replace the USERNAME & TOKEN with actual values)
# 4) Run sudo apt install jq : To install jq library, used in the script.
# 5) Provide req. premissions to the file : chmod 777 list-collaborators.sh
# 6) Execute the script : ./list-collaborators.sh

# GitHub API URL
API_URL="https://api.github.com"

# GitHub username and personal access token
USERNAME=$username
TOKEN=$token


# Function to make a GET request to the GitHub API
function github_api_get {
    local endpoint="$1"
    local url="${API_URL}/${endpoint}"

    # Send a GET request to the GitHub API with authentication
    curl -s -u "${USERNAME}:${TOKEN}" "$url"
}

# Function to list users with read access to the repository
function list_users_with_read_access {
    local endpoint="repos/${REPO_OWNER}/${REPO_NAME}/collaborators"

    # Fetch the list of collaborators on the repository
#    collaborators1="$(github_api_get "$endpoint")
 #   echo "$collaborators1"
    collaborators="$(github_api_get "$endpoint" | jq -r '.[] | select(.permissions.pull == true) | .login')"

    # Display the list of collaborators with read access
    if [[ -z "$collaborators" ]]; then
        echo "No users with read access found for ${REPO_OWNER}/${REPO_NAME}."
    else
        echo "Users with read access to ${REPO_OWNER}/${REPO_NAME}:"
        echo "$collaborators"
    fi
}

# Main script

# Take input from the user - Owner name and Repo name
while [[ -z "$REPO_OWNER" ]]; do
  read -p "Enter the owner name: " REPO_OWNER
done

while [[ -z "$REPO_NAME" ]]; do
  read -p "Enter the repo name: " REPO_NAME
done


echo "Listing users with read access to ${REPO_OWNER}/${REPO_NAME}..."
list_users_with_read_access